#!/bin/bash

#     __
#    / /_  _________ _      ______ ___
#   / __ \/ ___/ __ \ | /| / / __ `__ \
#  / /_/ (__  ) /_/ / |/ |/ / / / / / /
# /_.___/____/ .___/|__/|__/_/ /_/ /_/
#           /_/
#

# Restore wallpaper
nitrogen --restore &

# Starting SXHKD Keyboard Daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch polybar theme
bash ~/.config/polybar/launch.sh --forest

# Enable transparency
picom -f --corner-radius 13 &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           7
bspc config focused_border_color "#7bc5e4"
bspc config normal_border_color  "#32344a"
bspc config active_border_color  "#444b6a"
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#bspc rule -a Terminator desktop='^3' follow=on
#bspc rule -a Firefox desktop='^1'
#bspc rule -a Code desktop='^2'
#bspc rule -a spotify desktop='^4'

